"""
train.py
========
Trains the Decision Tree classifier on the extracted feature matrix.

Pipeline:
  1. Load data/features.csv
  2. Encode class labels
  3. Stratified 80/20 train-test split
  4. 5-fold GridSearchCV to find optimal hyperparameters
  5. Train final Decision Tree with best params + cost-complexity pruning
  6. Save trained model to models/decision_tree_model.pkl

Usage:
    python src/train.py
"""

import os
import sys
import pickle
import numpy as np
import pandas as pd

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

# ──────────────────────────────────────────────
# Configuration
# ──────────────────────────────────────────────
FEATURES_CSV = "data/features.csv"
MODEL_PATH   = "models/decision_tree_model.pkl"
RANDOM_STATE = 42
TEST_SIZE    = 0.20


# ──────────────────────────────────────────────
# Step 1 — Load feature matrix
# ──────────────────────────────────────────────
def load_features(csv_path: str = FEATURES_CSV):
    """
    Load the feature CSV generated by feature_extraction.py.

    Returns:
        X: Feature matrix (n_samples, 10)
        y: Encoded integer labels (n_samples,)
        le: Fitted LabelEncoder for inverse_transform
    """
    if not os.path.exists(csv_path):
        sys.exit(
            f"[ERROR] Feature file not found: {csv_path}\n"
            "        Run src/feature_extraction.py first."
        )

    df = pd.read_csv(csv_path)
    print(f"[OK] Loaded feature matrix: {df.shape[0]} samples × {df.shape[1]} columns")

    # Separate features from label
    X = df.drop(columns=["label"]).values.astype(np.float32)
    y_raw = df["label"].values

    # Encode string labels to integers
    le = LabelEncoder()
    y = le.fit_transform(y_raw)

    print(f"     Classes: {list(le.classes_)}")
    print(f"     Label encoding: {dict(zip(le.classes_, le.transform(le.classes_)))}")

    return X, y, le


# ──────────────────────────────────────────────
# Step 2 — Train/test split
# ──────────────────────────────────────────────
def split_data(X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE):
    """
    Stratified 80/20 train-test split preserving class proportions.
    """
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=test_size,
        random_state=random_state,
        stratify=y                    # preserves class balance in both splits
    )
    print(f"\n[OK] Train samples: {len(X_train)} | Test samples: {len(X_test)}")
    return X_train, X_test, y_train, y_test


# ──────────────────────────────────────────────
# Step 3 — GridSearchCV hyperparameter tuning
# ──────────────────────────────────────────────
def run_grid_search(X_train, y_train):
    """
    5-fold stratified cross-validation grid search to find the optimal
    combination of Decision Tree hyperparameters.

    Hyperparameter grid (from project synopsis):
        criterion        : gini, entropy
        max_depth        : 5, 8, 10, 12, 15, 20
        min_samples_split: 2, 5, 10, 20
        min_samples_leaf : 1, 3, 5, 10
        max_features     : sqrt, log2, None
        ccp_alpha        : 0.0, 0.001, 0.005

    Returns:
        Best estimator and its parameters.
    """
    print("\n[INFO] Running 5-fold GridSearchCV — this may take a few minutes...")

    param_grid = {
        "criterion":         ["gini", "entropy"],
        "max_depth":         [5, 8, 10, 12, 15, 20],
        "min_samples_split": [2, 5, 10, 20],
        "min_samples_leaf":  [1, 3, 5, 10],
        "max_features":      ["sqrt", "log2", None],
        "ccp_alpha":         [0.0, 0.001, 0.005],
    }

    base_clf = DecisionTreeClassifier(random_state=RANDOM_STATE)
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

    grid_search = GridSearchCV(
        estimator=base_clf,
        param_grid=param_grid,
        cv=cv,
        scoring="accuracy",
        n_jobs=-1,           # use all CPU cores
        verbose=1
    )

    grid_search.fit(X_train, y_train)

    print(f"\n[OK] GridSearchCV complete.")
    print(f"     Best CV accuracy : {grid_search.best_score_:.4f}")
    print(f"     Best parameters  : {grid_search.best_params_}")

    return grid_search.best_estimator_, grid_search.best_params_


# ──────────────────────────────────────────────
# Step 4 — Train with best params (or defaults)
# ──────────────────────────────────────────────
def train_model(X_train, y_train, best_params: dict = None):
    """
    Train the final Decision Tree classifier.

    If best_params is provided (from GridSearchCV), those are used.
    Otherwise, the optimal values from the project synopsis are used:
        criterion=gini, max_depth=12, min_samples_split=10,
        min_samples_leaf=5, max_features=sqrt, ccp_alpha=0.001

    Args:
        X_train:     Training feature matrix.
        y_train:     Training labels.
        best_params: Dict of hyperparameters (optional).

    Returns:
        Trained DecisionTreeClassifier.
    """
    if best_params is None:
        # Optimal hyperparameters from project synopsis
        best_params = {
            "criterion":         "gini",
            "max_depth":         12,
            "min_samples_split": 10,
            "min_samples_leaf":  5,
            "max_features":      "sqrt",
            "ccp_alpha":         0.001,
        }
        print("[INFO] Using default optimal hyperparameters from synopsis.")

    clf = DecisionTreeClassifier(
        random_state=RANDOM_STATE,
        **best_params
    )

    clf.fit(X_train, y_train)
    print(f"\n[OK] Model trained.")
    print(f"     Tree depth   : {clf.get_depth()}")
    print(f"     Leaf nodes   : {clf.get_n_leaves()}")

    return clf


# ──────────────────────────────────────────────
# Step 5 — Quick evaluation during training
# ──────────────────────────────────────────────
def quick_evaluate(clf, X_test, y_test, label_encoder):
    """
    Print accuracy and classification report on the test set.
    Full visualizations are generated by evaluate.py.
    """
    y_pred = clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    print(f"\n{'='*50}")
    print(f"  TEST SET ACCURACY: {acc * 100:.2f}%")
    print(f"{'='*50}")
    print("\nClassification Report:")
    print(classification_report(
        y_test, y_pred,
        target_names=label_encoder.classes_
    ))

    return acc


# ──────────────────────────────────────────────
# Step 6 — Save model to disk
# ──────────────────────────────────────────────
def save_model(clf, label_encoder, model_path: str = MODEL_PATH):
    """
    Serialize the trained model and label encoder using Pickle.

    Saves a dict containing both objects so they can be reloaded together.
    """
    os.makedirs(os.path.dirname(model_path), exist_ok=True)

    model_bundle = {
        "classifier":    clf,
        "label_encoder": label_encoder
    }

    with open(model_path, "wb") as f:
        pickle.dump(model_bundle, f)

    size_kb = os.path.getsize(model_path) / 1024
    print(f"\n[OK] Model saved → {model_path}  ({size_kb:.1f} KB)")


# ──────────────────────────────────────────────
# Load model helper (used by predict.py & app.py)
# ──────────────────────────────────────────────
def load_model(model_path: str = MODEL_PATH):
    """
    Load the saved model bundle from disk.

    Returns:
        (classifier, label_encoder) tuple.
    """
    if not os.path.exists(model_path):
        sys.exit(
            f"[ERROR] Model not found: {model_path}\n"
            "        Run src/train.py first."
        )

    with open(model_path, "rb") as f:
        bundle = pickle.load(f)

    return bundle["classifier"], bundle["label_encoder"]


# ──────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────
if __name__ == "__main__":
    print("=" * 55)
    print("  Crop Disease Detection — Model Training")
    print("=" * 55)

    # 1. Load features
    X, y, le = load_features()

    # 2. Split data
    X_train, X_test, y_train, y_test = split_data(X, y)

    # 3. GridSearchCV (set run_gridsearch=True to enable — takes longer)
    run_gridsearch = False    # Change to True to run full grid search
    if run_gridsearch:
        best_clf, best_params = run_grid_search(X_train, y_train)
        clf = best_clf
    else:
        clf = train_model(X_train, y_train)

    # 4. Evaluate
    quick_evaluate(clf, X_test, y_test, le)

    # 5. Save
    save_model(clf, le)

    print("\n[DONE] Training complete. Run src/evaluate.py for full plots.")
